name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
        gemfile:
          - gemfiles/rails_4_2.gemfile
          - gemfiles/rails_5_0.gemfile
          - gemfiles/rails_5_1.gemfile
          - gemfiles/rails_5_2.gemfile
          - gemfiles/rails_6_0.gemfile
        db:
          - sqlite
          - mysql
          - postgresql
        exclude:
          - ruby: 2.6.4
            gemfile: gemfiles/rails_4_2.gemfile
          - ruby: 2.7.0
            gemfile: gemfiles/rails_4_2.gemfile
          - ruby: 2.3.8
            gemfile: gemfiles/rails_6_0.gemfile
          - ruby: 2.4.7
            gemfile: gemfiles/rails_6_0.gemfile
    name: 'Ruby: ${{ matrix.ruby }} Gemfile: ${{ matrix.gemfile }} DB: ${{ matrix.db }}'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: devise_token_auth_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
          POSTGRES_DB: devise_token_auth_test
        ports:
          - 5432:5432
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RAILS_ENV: test
      DB: ${{ matrix.db }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Bundler 1.x for Rails 4.2
        if: ${{ matrix.gemfile == 'gemfiles/rails_4_2.gemfile' || matrix.gemfile == 'gemfiles/rails_4_2_mongoid_5.gemfile' }}
        run: echo "BUNDLER_VERSION=1.17.3" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: ${{ env.BUNDLER_VERSION || '2.2.9' }}
      - run: |
          bundle exec rake --trace db:migrate
          bundle exec rake
